[package]
name = "reverse-polish"
version = "0.1.0"
authors = ["choimake <choimake330@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
anyhow = "1.0"